name: CI Pipeline

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: ./mvnw -B test

      - name: Build app
        run: ./mvnw -B clean package

      - name: Docker build
        run: docker build -f cd.dockerfile -t spring-app .

      - name: Build documentation
        run: ./mvnw -B javadoc:javadoc

        # -------------------------
        # CD — main branch only
        # -------------------------

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image (tag=main)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -f cd.dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-app:main .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-app:main

      - name: Install Netlify CLI
        if: github.ref == 'refs/heads/main'
        run: npm install -g netlify-cli

      - name: Build Javadoc
        run: ./mvnw javadoc:javadoc

      - name: Deploy documentation to Netlify (--prod)
        if: github.ref == 'refs/heads/main'
        run: |
          netlify deploy \
            --dir=target/site/apidocs \
            --prod \
            --auth="${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            --site="${{ secrets.NETLIFY_SITE_ID }}"
